// flow-typed signature: de965626e812ea9d4ac4ea956a7f6ed1
// flow-typed version: <<STUB>>/@size-limit/file_v^8.0.0/flow_v0.187.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@size-limit/file'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@size-limit/file' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@size-limit/file/index' {
  declare module.exports: $Exports<'@size-limit/file'>;
}
declare module '@size-limit/file/index.js' {
  declare module.exports: $Exports<'@size-limit/file'>;
}
