// flow-typed signature: b46b9f972af2ddb65c21f258f59b802a
// flow-typed version: <<STUB>>/@size-limit/webpack_v^8.0.0/flow_v0.187.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@size-limit/webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@size-limit/webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@size-limit/webpack/convert-config' {
  declare module.exports: any;
}

declare module '@size-limit/webpack/get-config' {
  declare module.exports: any;
}

declare module '@size-limit/webpack/run-webpack' {
  declare module.exports: any;
}

// Filename aliases
declare module '@size-limit/webpack/convert-config.js' {
  declare module.exports: $Exports<'@size-limit/webpack/convert-config'>;
}
declare module '@size-limit/webpack/get-config.js' {
  declare module.exports: $Exports<'@size-limit/webpack/get-config'>;
}
declare module '@size-limit/webpack/index' {
  declare module.exports: $Exports<'@size-limit/webpack'>;
}
declare module '@size-limit/webpack/index.js' {
  declare module.exports: $Exports<'@size-limit/webpack'>;
}
declare module '@size-limit/webpack/run-webpack.js' {
  declare module.exports: $Exports<'@size-limit/webpack/run-webpack'>;
}
