// flow-typed signature: 69d6c7cc5fca9b6949024b3d347b4232
// flow-typed version: <<STUB>>/eslint-import-resolver-typescript_v^2.4.0/flow_v0.187.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-typescript'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-typescript' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-import-resolver-typescript/lib/cjs' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-typescript/lib/es2015' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-typescript/lib/esm' {
  declare module.exports: any;
}

declare module 'eslint-import-resolver-typescript/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-import-resolver-typescript/lib/cjs.js' {
  declare module.exports: $Exports<'eslint-import-resolver-typescript/lib/cjs'>;
}
declare module 'eslint-import-resolver-typescript/lib/es2015.js' {
  declare module.exports: $Exports<'eslint-import-resolver-typescript/lib/es2015'>;
}
declare module 'eslint-import-resolver-typescript/lib/esm.js' {
  declare module.exports: $Exports<'eslint-import-resolver-typescript/lib/esm'>;
}
declare module 'eslint-import-resolver-typescript/lib/index' {
  declare module.exports: $Exports<'eslint-import-resolver-typescript/lib'>;
}
declare module 'eslint-import-resolver-typescript/lib/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-typescript/lib'>;
}
