// flow-typed signature: a3bf66d9bcb188c3eed94b8fb67b5e8b
// flow-typed version: <<STUB>>/markdown-magic_v^2.6.0/flow_v0.187.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-magic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-magic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-magic/cli-utils' {
  declare module.exports: any;
}

declare module 'markdown-magic/cli' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/processFile' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/transforms/code' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/transforms/file' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/transforms' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/transforms/remote' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/transforms/toc' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/updateContents' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/utils/_md.test' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/utils/new-parser' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/utils/new-parser.test' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/utils/regex' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/utils/remoteRequest' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/utils/sortOrder' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/utils/weird-parse' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/utils/weird-parse.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-magic/cli-utils.js' {
  declare module.exports: $Exports<'markdown-magic/cli-utils'>;
}
declare module 'markdown-magic/cli.js' {
  declare module.exports: $Exports<'markdown-magic/cli'>;
}
declare module 'markdown-magic/index' {
  declare module.exports: $Exports<'markdown-magic'>;
}
declare module 'markdown-magic/index.js' {
  declare module.exports: $Exports<'markdown-magic'>;
}
declare module 'markdown-magic/lib/index' {
  declare module.exports: $Exports<'markdown-magic/lib'>;
}
declare module 'markdown-magic/lib/index.js' {
  declare module.exports: $Exports<'markdown-magic/lib'>;
}
declare module 'markdown-magic/lib/processFile.js' {
  declare module.exports: $Exports<'markdown-magic/lib/processFile'>;
}
declare module 'markdown-magic/lib/transforms/code.js' {
  declare module.exports: $Exports<'markdown-magic/lib/transforms/code'>;
}
declare module 'markdown-magic/lib/transforms/file.js' {
  declare module.exports: $Exports<'markdown-magic/lib/transforms/file'>;
}
declare module 'markdown-magic/lib/transforms/index' {
  declare module.exports: $Exports<'markdown-magic/lib/transforms'>;
}
declare module 'markdown-magic/lib/transforms/index.js' {
  declare module.exports: $Exports<'markdown-magic/lib/transforms'>;
}
declare module 'markdown-magic/lib/transforms/remote.js' {
  declare module.exports: $Exports<'markdown-magic/lib/transforms/remote'>;
}
declare module 'markdown-magic/lib/transforms/toc.js' {
  declare module.exports: $Exports<'markdown-magic/lib/transforms/toc'>;
}
declare module 'markdown-magic/lib/updateContents.js' {
  declare module.exports: $Exports<'markdown-magic/lib/updateContents'>;
}
declare module 'markdown-magic/lib/utils/_md.test.js' {
  declare module.exports: $Exports<'markdown-magic/lib/utils/_md.test'>;
}
declare module 'markdown-magic/lib/utils/new-parser.js' {
  declare module.exports: $Exports<'markdown-magic/lib/utils/new-parser'>;
}
declare module 'markdown-magic/lib/utils/new-parser.test.js' {
  declare module.exports: $Exports<'markdown-magic/lib/utils/new-parser.test'>;
}
declare module 'markdown-magic/lib/utils/regex.js' {
  declare module.exports: $Exports<'markdown-magic/lib/utils/regex'>;
}
declare module 'markdown-magic/lib/utils/remoteRequest.js' {
  declare module.exports: $Exports<'markdown-magic/lib/utils/remoteRequest'>;
}
declare module 'markdown-magic/lib/utils/sortOrder.js' {
  declare module.exports: $Exports<'markdown-magic/lib/utils/sortOrder'>;
}
declare module 'markdown-magic/lib/utils/weird-parse.js' {
  declare module.exports: $Exports<'markdown-magic/lib/utils/weird-parse'>;
}
declare module 'markdown-magic/lib/utils/weird-parse.test.js' {
  declare module.exports: $Exports<'markdown-magic/lib/utils/weird-parse.test'>;
}
