// flow-typed signature: c54f21b8b4757eaadae262c53591c9bc
// flow-typed version: <<STUB>>/remark-lint_v^8.0.0/flow_v0.187.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-lint/index' {
  declare module.exports: $Exports<'remark-lint'>;
}
declare module 'remark-lint/index.js' {
  declare module.exports: $Exports<'remark-lint'>;
}
