// flow-typed signature: d04a17a123d4a613f506b0d998152aef
// flow-typed version: <<STUB>>/size-limit_v^8.0.0/flow_v0.187.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'size-limit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'size-limit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'size-limit/bin' {
  declare module.exports: any;
}

declare module 'size-limit/calc' {
  declare module.exports: any;
}

declare module 'size-limit/create-help' {
  declare module.exports: any;
}

declare module 'size-limit/create-reporter' {
  declare module.exports: any;
}

declare module 'size-limit/debug' {
  declare module.exports: any;
}

declare module 'size-limit/get-config' {
  declare module.exports: any;
}

declare module 'size-limit/load-plugins' {
  declare module.exports: any;
}

declare module 'size-limit/parse-args' {
  declare module.exports: any;
}

declare module 'size-limit/process-import' {
  declare module.exports: any;
}

declare module 'size-limit/read-pkg-up' {
  declare module.exports: any;
}

declare module 'size-limit/rm' {
  declare module.exports: any;
}

declare module 'size-limit/run' {
  declare module.exports: any;
}

declare module 'size-limit/size-limit-error' {
  declare module.exports: any;
}

// Filename aliases
declare module 'size-limit/bin.js' {
  declare module.exports: $Exports<'size-limit/bin'>;
}
declare module 'size-limit/calc.js' {
  declare module.exports: $Exports<'size-limit/calc'>;
}
declare module 'size-limit/create-help.js' {
  declare module.exports: $Exports<'size-limit/create-help'>;
}
declare module 'size-limit/create-reporter.js' {
  declare module.exports: $Exports<'size-limit/create-reporter'>;
}
declare module 'size-limit/debug.js' {
  declare module.exports: $Exports<'size-limit/debug'>;
}
declare module 'size-limit/get-config.js' {
  declare module.exports: $Exports<'size-limit/get-config'>;
}
declare module 'size-limit/index' {
  declare module.exports: $Exports<'size-limit'>;
}
declare module 'size-limit/index.js' {
  declare module.exports: $Exports<'size-limit'>;
}
declare module 'size-limit/load-plugins.js' {
  declare module.exports: $Exports<'size-limit/load-plugins'>;
}
declare module 'size-limit/parse-args.js' {
  declare module.exports: $Exports<'size-limit/parse-args'>;
}
declare module 'size-limit/process-import.js' {
  declare module.exports: $Exports<'size-limit/process-import'>;
}
declare module 'size-limit/read-pkg-up.js' {
  declare module.exports: $Exports<'size-limit/read-pkg-up'>;
}
declare module 'size-limit/rm.js' {
  declare module.exports: $Exports<'size-limit/rm'>;
}
declare module 'size-limit/run.js' {
  declare module.exports: $Exports<'size-limit/run'>;
}
declare module 'size-limit/size-limit-error.js' {
  declare module.exports: $Exports<'size-limit/size-limit-error'>;
}
