// flow-typed signature: 42ebd33712f2de5fc3a2416861bde874
// flow-typed version: <<STUB>>/slackify-markdown_v^4.3.1/flow_v0.187.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slackify-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slackify-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slackify-markdown/src/definitions' {
  declare module.exports: any;
}

declare module 'slackify-markdown/src' {
  declare module.exports: any;
}

declare module 'slackify-markdown/src/slackify' {
  declare module.exports: any;
}

declare module 'slackify-markdown/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slackify-markdown/index' {
  declare module.exports: $Exports<'slackify-markdown'>;
}
declare module 'slackify-markdown/index.js' {
  declare module.exports: $Exports<'slackify-markdown'>;
}
declare module 'slackify-markdown/src/definitions.js' {
  declare module.exports: $Exports<'slackify-markdown/src/definitions'>;
}
declare module 'slackify-markdown/src/index' {
  declare module.exports: $Exports<'slackify-markdown/src'>;
}
declare module 'slackify-markdown/src/index.js' {
  declare module.exports: $Exports<'slackify-markdown/src'>;
}
declare module 'slackify-markdown/src/slackify.js' {
  declare module.exports: $Exports<'slackify-markdown/src/slackify'>;
}
declare module 'slackify-markdown/src/utils.js' {
  declare module.exports: $Exports<'slackify-markdown/src/utils'>;
}
