// flow-typed signature: 26d43cd8e46ad0ceecc2af08cd73edc6
// flow-typed version: <<STUB>>/zx_v^7.0.7/flow_v0.187.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'zx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'zx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'zx/build/cli' {
  declare module.exports: any;
}

declare module 'zx/build/core' {
  declare module.exports: any;
}

declare module 'zx/build/experimental' {
  declare module.exports: any;
}

declare module 'zx/build/globals' {
  declare module.exports: any;
}

declare module 'zx/build/goods' {
  declare module.exports: any;
}

declare module 'zx/build' {
  declare module.exports: any;
}

declare module 'zx/build/repl' {
  declare module.exports: any;
}

declare module 'zx/build/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'zx/build/cli.js' {
  declare module.exports: $Exports<'zx/build/cli'>;
}
declare module 'zx/build/core.js' {
  declare module.exports: $Exports<'zx/build/core'>;
}
declare module 'zx/build/experimental.js' {
  declare module.exports: $Exports<'zx/build/experimental'>;
}
declare module 'zx/build/globals.js' {
  declare module.exports: $Exports<'zx/build/globals'>;
}
declare module 'zx/build/goods.js' {
  declare module.exports: $Exports<'zx/build/goods'>;
}
declare module 'zx/build/index' {
  declare module.exports: $Exports<'zx/build'>;
}
declare module 'zx/build/index.js' {
  declare module.exports: $Exports<'zx/build'>;
}
declare module 'zx/build/repl.js' {
  declare module.exports: $Exports<'zx/build/repl'>;
}
declare module 'zx/build/util.js' {
  declare module.exports: $Exports<'zx/build/util'>;
}
